/**
 * ManualAccess.jsx
 * Maintenance > Training manual access — who may read the public owner manual
 * (/Training-Manual): anyone with the link, or only people holding a passcode
 * the owner made for them, each with its own time limit.
 * Route: /owner/maintenance/manual-access
 *
 * A passcode is generated by the server and shown here exactly once. Only a
 * keyed hash of it is stored, so it can never be shown again — lose one and
 * make another. The limits are enforced by the server every time the manual is
 * opened, not by anything on this screen.
 */
import { useState, useEffect, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../../api'
import { CONFIG } from '../../config'
import { DEFAULT_VILLA_ID } from '../../utils/villaContext'
import { guestBaseUrl } from '../../utils/guestMessages'
import { whenLong, whenShort, timeLeft } from '../../utils/localWhen'

const LIMITS = [
  { value: '2',     label: '2 hours' },
  { value: '24',    label: '1 day' },
  { value: '72',    label: '3 days' },
  { value: '168',   label: '7 days' },
  { value: '336',   label: '14 days' },
  { value: '720',   label: '30 days' },
  { value: 'never', label: 'No time limit' },
]
const toHours = v => (v === 'never' ? 'never' : Number(v))

const STATUS = {
  active:  { label: 'ACTIVE',  color: '#34A853', bg: 'rgba(52,168,83,0.15)' },
  expired: { label: 'EXPIRED', color: '#F59E0B', bg: 'rgba(245,158,11,0.15)' },
  revoked: { label: 'REVOKED', color: '#EF4444', bg: 'rgba(239,68,68,0.15)' },
}

const inp = { width: '100%', padding: '10px 12px', borderRadius: '8px', border: '1px solid var(--border-dim)',
  background: 'var(--dark-input)', color: '#EDF2F7', fontSize: '0.9rem', boxSizing: 'border-box' }
const smallBtn = (hue) => ({ fontSize: '0.76rem', fontWeight: 700, padding: '8px 12px', borderRadius: '8px', cursor: 'pointer',
  background: `rgba(${hue},0.1)`, border: `1px solid rgba(${hue},0.3)`, color: `rgb(${hue})` })

export default function ManualAccess() {
  const navigate = useNavigate()
  const [data, setData]       = useState(null)
  const [loadErr, setLoadErr] = useState('')
  const [toast, setToast]     = useState(null)
  const [busy, setBusy]       = useState(null)      // 'mode' | 'create' | a passcode id
  const [fresh, setFresh]     = useState(null)      // { code, label, expiresAt } — shown once
  const [label, setLabel]     = useState('')
  const [limit, setLimit]     = useState('168')

  const manualUrl = `${guestBaseUrl()}/Training-Manual`
  const showToast = (msg, type = 'success') => { setToast({ msg, type }); setTimeout(() => setToast(null), 3500) }

  const load = useCallback(() => {
    api.getManualAccess(DEFAULT_VILLA_ID)
      .then(d => { setData(d); setLoadErr('') })
      .catch(e => setLoadErr(e?.message || 'Could not load'))
  }, [])
  useEffect(() => { load() }, [load])

  async function copy(text, done) {
    try { await navigator.clipboard.writeText(text); showToast(done) }
    catch { window.prompt('Copy this', text) }   // clipboard refused — hand it over to copy by hand
  }

  async function chooseMode(next) {
    if (!data || next === data.mode) return
    if (next === 'passcode' && !window.confirm(
      'Only people holding a passcode — and you, whenever you are signed in — will be able to read the manual. ' +
      'Anyone using the plain link will see a passcode screen instead.\n\nSwitch now?')) return
    setBusy('mode')
    try {
      await api.setManualAccessMode({ villaId: DEFAULT_VILLA_ID, mode: next })
      showToast(next === 'passcode' ? 'Now: passcode only ✓' : 'Now: open to anyone with the link ✓')
      load()
    } catch (e) { showToast(e?.message || 'Could not change it', 'error') }
    finally { setBusy(null) }
  }

  async function create() {
    if (!label.trim()) { showToast('Say who the passcode is for', 'error'); return }
    setBusy('create')
    try {
      const r = await api.createManualPasscode({ villaId: DEFAULT_VILLA_ID, label: label.trim(), validForHours: toHours(limit) })
      setFresh({ code: r.code, label: r.label, expiresAt: r.expiresAt })
      setLabel('')
      load()
    } catch (e) { showToast(e?.message || 'Could not make a passcode', 'error') }
    finally { setBusy(null) }
  }

  async function revoke(p) {
    if (!window.confirm(`Revoke the passcode for "${p.label}"? It stops working immediately and cannot be brought back.`)) return
    setBusy(p.id)
    try { await api.revokeManualPasscode({ passcodeId: p.id }); showToast('Revoked ✓'); load() }
    catch (e) { showToast(e?.message || 'Could not revoke', 'error') }
    finally { setBusy(null) }
  }

  async function retime(p, value) {
    if (!value) return
    const text = LIMITS.find(l => l.value === value)?.label || value
    const ask = value === 'never'
      ? `Remove the time limit on "${p.label}"? It will work until you revoke it.`
      : `Make "${p.label}" valid for another ${text}, counted from now?`
    if (!window.confirm(ask)) return
    setBusy(p.id)
    try { await api.setManualPasscodeExpiry({ passcodeId: p.id, validForHours: toHours(value) }); showToast('Time limit updated ✓'); load() }
    catch (e) { showToast(e?.message || 'Could not update', 'error') }
    finally { setBusy(null) }
  }

  // What the owner sends. Plain words and no emoji, so it survives WhatsApp's
  // prefilled-text path on Windows intact.
  const inviteText = f => [
    `${CONFIG.brandName} — owner training manual`,
    manualUrl,
    `Passcode: ${f.code}`,
    f.expiresAt ? `Valid until ${whenLong(f.expiresAt)}` : 'No time limit',
  ].join('\n')

  const open = data?.mode === 'open'
  const activeCount = (data?.passcodes || []).filter(p => p.status === 'active').length

  return (
    <div className="screen">
      <div className="topbar">
        <button className="back-btn" onClick={() => navigate(-1)}>‹</button>
        <div>
          <div className="topbar-title">Training manual access</div>
          <div className="topbar-sub">MAINTENANCE · WHO CAN READ THE MANUAL</div>
        </div>
        <div style={{ width: 34 }} />
      </div>

      <div className="screen-body">

        {/* ── The address ───────────────────────────── */}
        <div className="card" style={{ marginBottom: '14px' }}>
          <div className="card-section-label" style={{ marginBottom: 6 }}>THE MANUAL'S ADDRESS</div>
          <div style={{ fontFamily: 'monospace', fontSize: '0.78rem', color: '#85B7EB', wordBreak: 'break-all', marginBottom: 10 }}>{manualUrl}</div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={() => copy(manualUrl, 'Link copied ✓')} style={smallBtn('200,144,58')}>📋 Copy link</button>
            <a href={manualUrl} target="_blank" rel="noreferrer" style={{ ...smallBtn('133,183,235'), textDecoration: 'none' }}>↗ Open it</a>
          </div>
        </div>

        {/* ── Who can read it ───────────────────────── */}
        <div className="card-section-label">WHO CAN READ IT</div>
        {loadErr && <div className="card" style={{ color: '#EF4444', fontSize: '0.85rem', marginBottom: 14 }}>{loadErr}</div>}
        {!data && !loadErr && <div className="loading"><div className="spinner" />Loading…</div>}
        {data && (
          <div style={{ display: 'grid', gap: 8, marginBottom: 14 }}>
            {[
              { id: 'open',     icon: '🌐', title: 'Anyone with the link',          sub: 'No passcode needed. Good for sharing widely.' },
              { id: 'passcode', icon: '🔐', title: 'Only people with a passcode',   sub: 'Everyone else sees a passcode screen. You are always let in when signed in.' },
            ].map(o => {
              const on = data.mode === o.id
              return (
                <button key={o.id} onClick={() => chooseMode(o.id)} disabled={busy === 'mode'}
                  style={{ textAlign: 'left', display: 'flex', gap: 12, alignItems: 'flex-start', padding: '12px 14px', borderRadius: 12, cursor: on ? 'default' : 'pointer',
                    background: on ? 'rgba(200,144,58,0.10)' : 'var(--dark-card)', border: `1px solid ${on ? 'rgba(200,144,58,0.5)' : 'var(--border-dim)'}`, color: 'var(--text)' }}>
                  <span style={{ fontSize: '1.3rem' }}>{o.icon}</span>
                  <span style={{ flex: 1 }}>
                    <span style={{ display: 'block', fontWeight: 700, fontSize: '0.9rem' }}>{o.title}</span>
                    <span style={{ display: 'block', fontSize: '0.76rem', color: 'var(--text-dim)', marginTop: 2 }}>{o.sub}</span>
                  </span>
                  <span style={{ fontSize: '0.65rem', fontWeight: 800, letterSpacing: 1, padding: '3px 9px', borderRadius: 10, whiteSpace: 'nowrap',
                    background: on ? 'rgba(52,168,83,0.15)' : 'transparent', color: on ? '#34A853' : 'var(--text-dim)', border: on ? 'none' : '1px solid var(--border-dim)' }}>
                    {on ? '● ON' : 'SWITCH'}
                  </span>
                </button>
              )
            })}
          </div>
        )}

        {/* ── Make a passcode ───────────────────────── */}
        <div className="card-section-label">NEW PASSCODE</div>
        <div className="card" style={{ marginBottom: 14 }}>
          <div className="field" style={{ marginBottom: 10 }}>
            <label className="field-label">Who is it for?</label>
            <input style={inp} value={label} maxLength={80} onChange={e => setLabel(e.target.value)}
              placeholder="e.g. Raj — Acme Travels" onKeyDown={e => { if (e.key === 'Enter') create() }} />
          </div>
          <div className="field" style={{ marginBottom: 12 }}>
            <label className="field-label">Valid for</label>
            <select style={inp} value={limit} onChange={e => setLimit(e.target.value)}>
              {LIMITS.map(l => <option key={l.value} value={l.value}>{l.label}</option>)}
            </select>
          </div>
          <button className="btn btn-gold" style={{ width: '100%' }} onClick={create} disabled={busy === 'create'}>
            {busy === 'create' ? 'Making it…' : 'Create passcode'}
          </button>
        </div>

        {/* ── The passcode, once ────────────────────── */}
        {fresh && (
          <div style={{ background: 'rgba(95,208,174,0.1)', border: '1px solid rgba(95,208,174,0.4)', borderRadius: 12, padding: 16, marginBottom: 16 }}>
            <div style={{ fontSize: '0.72rem', color: '#5FD0AE', letterSpacing: 1, marginBottom: 8 }}>
              PASSCODE FOR {fresh.label.toUpperCase()} — SHOWN ONCE
            </div>
            <div style={{ fontSize: '2rem', fontWeight: 800, letterSpacing: 5, color: '#fff', fontFamily: 'monospace', marginBottom: 4, wordBreak: 'break-all' }}>
              {fresh.code}
            </div>
            <div style={{ fontSize: '0.8rem', color: '#C9D4E2', marginBottom: 10 }}>
              {fresh.expiresAt ? <>Valid until <b>{whenLong(fresh.expiresAt)}</b></> : <b>No time limit</b>}
            </div>
            {open && (
              <div style={{ fontSize: '0.76rem', color: '#F59E0B', background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.3)', borderRadius: 8, padding: '8px 10px', marginBottom: 10, lineHeight: 1.5 }}>
                The manual is open to anyone right now, so this passcode isn't needed yet.{' '}
                <button onClick={() => chooseMode('passcode')} style={{ background: 'none', border: 'none', color: '#F59E0B', fontWeight: 800, textDecoration: 'underline', cursor: 'pointer', padding: 0, fontSize: 'inherit' }}>
                  Require a passcode now
                </button>
              </div>
            )}
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 10 }}>
              <button onClick={() => copy(inviteText(fresh), 'Message copied ✓')} style={smallBtn('200,144,58')}>📋 Copy message</button>
              <a href={`https://wa.me/?text=${encodeURIComponent(inviteText(fresh))}`} target="_blank" rel="noreferrer"
                style={{ ...smallBtn('37,211,102'), textDecoration: 'none' }}>💬 WhatsApp</a>
              <button onClick={() => copy(`${manualUrl}?code=${fresh.code.replace('-', '')}`, 'One-tap link copied ✓')} style={smallBtn('133,183,235')}>🔗 One-tap link</button>
            </div>
            <div style={{ fontSize: '0.72rem', color: '#9AA5B4', marginBottom: 12, lineHeight: 1.5 }}>
              Only a scrambled version is stored, so this can't be shown again. If it gets lost, make a new one.
              The one-tap link has the passcode built in, so the person doesn't have to type it.
            </div>
            <button className="btn" style={{ width: '100%' }} onClick={() => setFresh(null)}>Done</button>
          </div>
        )}

        {/* ── Existing passcodes ────────────────────── */}
        <div className="card-section-label">PASSCODES{data?.passcodes?.length ? ` · ${activeCount} ACTIVE` : ''}</div>
        {data && !data.passcodes.length && (
          <div className="card" style={{ textAlign: 'center', padding: 22, color: 'var(--text-dim)', fontSize: '0.85rem' }}>
            No passcodes yet. Make one above for each person you want to give access to.
          </div>
        )}
        {data?.passcodes?.length > 0 && (
          <div style={{ background: 'var(--dark-card)', borderRadius: 12, border: '1px solid var(--border-dim)', overflow: 'hidden' }}>
            {data.passcodes.map((p, i) => {
              const s = STATUS[p.status]
              return (
                <div key={p.id} style={{ padding: '14px 16px', borderBottom: i < data.passcodes.length - 1 ? '1px solid var(--border-dim)' : 'none', opacity: p.status === 'active' ? 1 : 0.6 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 8, marginBottom: 3 }}>
                    <div style={{ fontWeight: 600, fontSize: '0.9rem', minWidth: 0, wordBreak: 'break-word' }}>{p.label}</div>
                    <span style={{ fontSize: '0.65rem', fontWeight: 700, padding: '2px 8px', borderRadius: 10, background: s.bg, color: s.color, whiteSpace: 'nowrap' }}>{s.label}</span>
                  </div>
                  <div style={{ fontSize: '0.74rem', color: p.status === 'active' ? '#C9D4E2' : 'var(--text-dim)', marginBottom: 2 }}>
                    {p.status === 'revoked' ? `Revoked ${whenShort(p.revokedAt)}`
                      : p.expiresAt ? (p.status === 'expired' ? `Expired ${whenShort(p.expiresAt)}` : `Until ${whenShort(p.expiresAt)} · ${timeLeft(p.expiresAt)}`)
                      : 'No time limit'}
                  </div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-dim)', marginBottom: 10 }}>
                    Made {whenShort(p.createdAt)} · {p.useCount ? `opened ${p.useCount}×, last ${whenShort(p.lastUsedAt)}` : 'not opened yet'}
                  </div>
                  {p.status !== 'revoked' && (
                    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
                      <select disabled={busy === p.id} value="" onChange={e => retime(p, e.target.value)}
                        style={{ ...inp, width: 'auto', fontSize: '0.76rem', padding: '8px 10px' }} aria-label="Change time limit">
                        <option value="">{p.status === 'expired' ? '⏱ Renew for…' : '⏱ Change time limit…'}</option>
                        {LIMITS.map(l => <option key={l.value} value={l.value}>{l.value === 'never' ? l.label : `Another ${l.label}`}</option>)}
                      </select>
                      <button onClick={() => revoke(p)} disabled={busy === p.id} style={smallBtn('239,68,68')}>🚫 Revoke</button>
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        )}

        <div style={{ marginTop: 14, fontSize: '0.7rem', color: '#5C7080', lineHeight: 1.6 }}>
          Time limits are checked by our server every time the manual is opened, and a page that is already open locks itself when its limit runs out.
          You are never locked out of your own manual while you are signed in.
        </div>
      </div>
      {toast && <div className={`toast ${toast.type}`}>{toast.msg}</div>}
    </div>
  )
}
