name = "bgindia-portal"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
DEFAULT_VILLA_ID = "dwarka"

[[d1_databases]]
binding = "DB"
database_name = "bgindia-db"
database_id = "6047aa03-9893-4fd9-8ba2-b3d7f5264ed1"

[[d1_databases]]
binding = "DB_ESTATES"
database_name = "bgindiadb-estates"
database_id = "6e23cb84-d341-4b2e-8062-e8244844309d"

[ai]
binding = "AI"
